server:
  servlet:
    context-path: /api
    
app: 
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/kaihangadb
    username: postgres
    password: digital
    pool-size: 30
    
spring:
  application:
    name: Kaihanga